import { cookies } from "next/headers";
import "./globals.css";
import { ReduxProvider } from "./providers";
import ReduxHydrate from "@/components/ReduxHydrate";
import { getAuthUser } from "@/lib/authService";

export const metadata = {
  title: "Hinode",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies()
  const token = (await cookieStore).get('auth_token')?.value
  const user = await getAuthUser(token)

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ReduxHydrate user={user} token={token} />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
